apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: lab-04-trigger-binding
  namespace: <your-namespace>
spec:
  params:
    - name: repo-url
      value: $(body.repository.clone_url)
    - name: revision
      value: $(body.ref)